### ISSUE TITLE
comment size, time to repost, receive these responses

### ISSUE THREAD

**Issue by HDInfautre** [akeeba/engage#101]
Hi,
I just spent a few hours testing, reading the documentation pages to change my default comment extension for joomla 4. 
Your extension suits me well :-) and I will have to adopt it for joomla
Nevertheless, I will suggest some additions one day ... if possible because I do not seem to have seen in the settings, plugin, documentation
1/ force to enter a size higher than x characters and lower than y characters. 
This would avoid "+1" or a 10 000 characters unreadable or taking all the page !
2/ time interval (minute) between 2 publications of comments to avoid spam
3/ to have the answer to his comment in his mailbox ?

The others are less important
3/ possibility to vote on a comment (to eventually make it go up if sorted)
4/ filter (backoffice) on a joomla member
5/ statistics on comments

Regards

**Comment by nikosdion** [comment]
> force to enter a size higher than x characters and lower than y characters.

The comments are HTML. We could strip tags and do a character count. Would that work for you? 

I am not going to implement HTML word count because this doesn't work in many Asian languages which do not have the concept of a space.

> time interval (minute) between 2 publications of comments to avoid spam

I am rejecting this outright. 

Time limits are just silly and no matter how meticulous you are in configuring them they can be TRIVIALLY circumvented, e.g. by using a 4G connection and a small army of free email accounts. Every time you restart the 4G connection (it takes all of a second or so) you get a new IP. Clear cookies, or use private / incognito mode in the browser, and you have a new session as well. Use your many email addresses and you have multiple identities / user accounts. So, what did you achieve with the time limit except pissing off legitimate users who are trying to post 1-2 liner comments on three different threads? Nothing. You just shot your feet. 

If you actually want to reduce spam use CAPTCHA and/or the Akismet integration. 

> to have the answer to his comment in his mailbox ?

They already receive replies to their comments unless they opt out of it. If your users don't receive those emails check your site's email setup and your email deliverability (have you set up SPF and DKIM?).

If you mean replying to the email to send a reply, I am rejecting this outright as well. Having done that for Akeeba Ticket System it's a pain in the ass, mostly for you trying to configure it. It is also very fun when you have two users who are on vacation and their vacation auto-responders start replying to each other. It is a never-ending loop of useless comments you can never, ever stop until at least one of them comes back to the office. Oof!

> filter (backoffice) on a joomla member

You can already search by email address.

There is a reason you cannot search by username: guest comments. It is possible for someone to have commented for a while as a guest user and then register a user account with the same email. If we were filtering by user ID / username we would not be listing their comments as a guest.

Filtering by email is also far more accurate than filtering by username. When you search for the username `foo` you will also see comments from users `foobar`, `the_foo` and `youcantfoolme` since there is a substring match of `foo` in all of these. Remember, that's how Joomla itself searches for usernames in the Users page. Speaking of which, you can of course search for a user in the Users page, copy their email and paste it to the search box in Engage.

> statistics on comments

I am rejecting this outright. 

You get the comment count per article and that's about it. Having posts per user or date range requires some database queries which are extremely slow. Making them faster would require removing guest comments and nested comment replies. I am not interested in doing that as I am not interested in making the interface painfully slow for a tertiary, vanity feature. The objective here is to create a FAST comment system.

**Comment by HDInfautre** [comment]
Hi,
Thank you for your quick and complete answer even if I am still surprised by the "rejecting" character. I do not work like that but anyway I respect especially for a very good free extension and maybe you are right ;-) 

1/ "The comments are HTML. We could strip tags and do a character count. would that work for you?"
yes of course :+1: , the minimum/maximum number to set is anyway a bit ... subjective :-)

2/ no miracle solution, I already had problems with or without this solution but I didn't know it could be bypassed that much !

4/ yes it is a solution, a little less flexible because additional step to copy/paste the email

As for the rest, I'll see that with the use of your plugin.
Thanks

Regards
(sorry for my bad English)

**Comment by nikosdion** [comment]
A feature request can be accepted (will be implemented) or rejected (will not be implemented). That's what I mean with the term "reject". I know that in other languages it can translate to different words with different subtle meanings, ranging from neutral to almost rude. I mean it in a neutral manner. That's why I explain why I am not accepting each feature, to give some context.

I will create an issue for the min/max character count. I can't promise when it will be implemented; the paid software has priority and Joomla 4 being released yesterday means we already have one big, paid extension to work on, plus our own site. Free extensions come after that. Such is life :)

**Comment by HDInfautre** [comment]
Hi,
Thank you for these clarifications and for taking into account a suggestion even without a deadline ;-)

**Comment by nikosdion** [comment]
I am closing this issue since this is now being tracked in #102
