### ISSUE TITLE
Styling issue after version 3 update

### ISSUE THREAD

**Issue by Razerr** [akeeba/engage#144]
Updated Akeeba Engage to version 3 and I have a najor styling issue regarding my articles. And it happens both on the template I am using right now as on the Cassiopeia. When the component is enabledthe whole content gets shrunken to the left of the page as in the [screenshot.](https://ibb.co/9hqL8jy) 

Thank you for any help.

**Comment by nikosdion** [comment]
Please install https://www.akeeba.com/download/developer-releases/engage-development/3-0-2-dev202201061337-reva4f112d.html and let me know if that fixed your problems.

PS: I am closing this issue because I had already written the code to address this issue before you filed the issue. You can still reply.

**Comment by Razerr** [comment]
Yes, problem fixed with that install :)
