### ISSUE TITLE
Where are my comments ?? (3.0.1/3.0.2)

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#160]
Since update from 2.0.5 to 3.0.1/3.0.2 my comments are not shown anymore (please see pic at end.)

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.0.5
* **PHP version**: 8.0.8
* **Am I using HTTPS**: Yes
* **Server Operating System**: Ubuntu Server 64 Bit
* **My device's Operating System**: Windows
* **My device's Operating System version**: Windows 10
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera
* **Browser version**: newest

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**:  Ver 15.1 Distrib 10.5.13-MariaDB
* **Server type**: Apache 2
* **Server version**: 2.4.48 (Ubuntu)
* **Hosting company / Local server**: Own Hosting
* **Server Operating System version**: Ubuntu Server 64 Bit

![wherecomments](https://user-images.githubusercontent.com/26506313/148662593-56d0c529-1ff0-41bb-b839-e473fbcf1e43.jpg)

**Comment by nikosdion** [comment]
I can see the comments just fine on Joomla 4.0.5 and Engage 3.0.2
![Screen Shot 2022-01-09 at 09 49 30](https://user-images.githubusercontent.com/256041/148673840-f04652d4-8ffa-495e-a38f-b613257ebeb4.png)

If you are using caching make sure to clear your cache. Engage 3.0.0 and 3.0.1 had a bug which prevented the comments from rendering when caching is enabled. If the missing comments situation are still cached the comments won't appear until you clear the cache. That was the reason I published 3.0.2.

**Comment by nikosdion** [comment]
I found a way that can be reproduced.

Go to Components, Engage, Options, Basic tab.

If the “Number of comments per page” is set to All or Use Global you see no comments. Set it to another value, e.g. 20. Comments are shown. The default for this option is 20.

There were two logic errors here. First, regardless of whether you were using Use Global (setting -1 in the database) or All (setting 0 in the database) it was converted to 0. Second, the value 0 would return no comments because of how PHP's array_slice works. 0 needs to be converted to NULL to get the entire array after an offset. Combining these two issues resulted in no comments.

I only spotted it because I had _one site_ where I had accidentally set this to All. On my dev and test sites I was always setting that to 20. I will release 3.0.3 tomorrow.

**Comment by NetSecond** [comment]
Hi,

you were right, I had set the option "Number of comments per page" to "all".
Now I set it to 50 and cleared the cache and everything is displayed.

BUT:

Now I have another problem:

In Options is ste: Maximum comment nesting: 3

But on frontpage, nesting is gone away.
Every comment and comment of comment is on same place and not nested.
I opened a new issue and hope, it is ok for you.

**Comment by nikosdion** [comment]
You just to check the option Load custom CSS. Don't open a new issue.
