### ISSUE TITLE
Akeeba Engage on a multilingual site does not integrate the language code in the URL of third languages.

### ISSUE THREAD

**Issue by Eddy-vh** [akeeba/engage#171]
Hello Nicholas.

Engage on a multilingual site does not return the content URLs according to the third language.

e.g.: French / English site with French as main language.
An English language site url would be www.site.com/en/blablabla.html.
Engage returns:
www.site.com/blablabla.html without the language code. See screenshot: https://dl.dropbox.com/s/zweg73rd4kyc9nx/Engage-multilingue.png

* **Joomla! version**: 3.10.5
* **PHP version**: 8.0.14
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows, macOS
* **My device's Operating System version**: e.g. macOS Monterey, Windows 10
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera, ...
* **Browser version**: the last

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: 5.5.5-10.3.32-MariaDB 
* **Server type**: Apache
* **Server version**: ???
* **Hosting company / Local server**: o2Switch (France)
* **Server Operating System version**: ???

Thank you very much.

Eddy

**Comment by nikosdion** [comment]
This cannot change because of the way Joomla's language management works. In a nutshell, the backend application and the frontend application are separate.

Even though we ask the frontend SEF router to create a link to the public URL of the article there is no way to have it correctly address language codes since they are not supported by the language plugin when it's loaded in the backend of the site.

Therefore the only thing we can do is completely remove this link.

**Comment by nikosdion** [comment]
It turns out that on _Joomla 4 only_ we **can** set the language and get the correct URL insofar the correct URL is the URL to the article for its stated language or, in case no language is set, the URL to the default language of the site. This does not seem to be at all possible on Joomla 3.

So, when you upgrade your site to Joomla 4 you will be able to get the correct URL. Until then, nothing much we can do ☹️

**Comment by Eddy-vh** [comment]
Hi,

Do not remove the link, this one being only in Backend and the administrator of the site having understood the principle, it will continue as currently.
The site will be migrated to Joomla 4 soon. ;)

Thanks for your reply and for Engage, which is a cool extension.

Thank you very much.

Eddy

**Comment by nikosdion** [comment]
I am not going to touch the Joomla 3 version — I have stopped working on it. As I said, on Joomla 4 it is possible to fix that so that's what I am going to do for Engage version 3 for Joomla 4.
