### ISSUE TITLE
Avatars from sources other than Gravatar

### ISSUE THREAD

**Issue by nikosdion** [akeeba/engage#18]
Ideas for further avatar plugins:
* Some popular Joomla extensions that offer user-uploaded avatars (TBD)
* Social Login has support for some services' avatars as well

IIRC Joomla 4 had core support for avatars? If I'm not mistaken that's something we should look into.

**Comment by breebee** [comment]
Use Cmavatar, 3 or 4 lines to update to joomla 4. Hands down best avatar system

**Comment by breebee** [comment]
Actually you should just fork it into akeeba engage. Simple, small, clean, flexible. If you would like I can send you the joomla 4 zip

**Comment by nikosdion** [comment]
I was mostly looking about third party services and extensions which the user might have already been using.

Besides, writing your own plugin to handle avatars is mostly pointless. Joomla 3 and 4 already support Custom Fields in the user profile. If I were to add support for something like that I would just let the administrator choose which custom field in the user profile contains the profile image and use some simple resizing code I already have to get the correct size. 

Whether even that makes sense is a big question. Why would anyone choose to set up yet another avatar in yet another service if they can use, for example, Avatar to achieve the same across multiple sites?

**Comment by breebee** [comment]
Hmmm.. I did not think about joomla custom fields, however no components support "joomla avatar" as an option since that would not make sense as a custom field. Also I dont think you should end up maintaining a bunch of avatar options since theres so many components out there that would be a mess and a pain. It think the best option for your development on engage would be to maintain a single  universal option that other maintainers like jomsocial, easyblog ect can integrate into their component with 2 lines of code. It would probably be less work for you to commit changes to their support of the "universal avatar" then vise versa. Just my thoughts, it is of course your project :) Maybe fork it into "Akeeba Avatar" and maintain it for the new wave of joomla 4 since cmavatar has not touched it in 4 years.

**Comment by nikosdion** [comment]
> It think the best option for your development on engage would be to maintain a single universal option that other maintainers like jomsocial, easyblog ect can integrate into their component with 2 lines of code.

Stop and think. They have not integrated **Gravatar** the past ten years, Gravatar being the de facto avatar service that's popular with blogs. Why the hell would they decide to give up their own custom crap and integrate with my avatar solution? They will never do that. So, no, your suggestion is actually the **exact opposite** of what is best for the development of Engage!

> Also I dont think you should end up maintaining a bunch of avatar options since theres so many components out there that would be a mess and a pain.

I agree as well. Since nobody wants to standardise I am closing this issue.
