### ISSUE TITLE
AJAX for comments

### ISSUE THREAD

**Issue by b2z** [akeeba/engage#25]
Thank you for your work and that you make it open source and free.

**Describe the solution you'd like**
We are living in the world of year 2020 ;) 
It would be very good to have AJAX on comment submission and possibly AJAX on comments listing.

**Comment by progreccor** [comment]
yes, we'd be very grateful for add such functionality in this extension

AJAX for submit comment desperately needed

**Comment by nikosdion** [comment]
No, I’m not going to implement this. This creates a hard dependency on JavaScript which has several problems. 

First, unless you accept JS on the domain as a user you don’t get to post anything. 

Second, you need to tell Joomla’s HTML editor to return the HTML for submission AND you need to reset its state after comment submission. The second part is not a given with most editors, even TinyMCE. Reloading a fresh editor through the not-quite-AJAX response wouldn’t work because half of the initialization is parameters set in JS or JSON blocks in the Joomla Document. Basically, I’d have to reload the page anyway. 

Third, you need to redisplay the new comment tree. This would essentially require a non-JSON return which is pure HTML or, alternatively, rendering the comments with JavaScript. The latter means that comments are invisible to users without JS enabled, has shoddy display performance and is incompatible with AJAX. 

The solution to all these problems is loading the entire comments section through an XHR request and using your own editor that doesn’t require initialization. This is slow, limits comments display only to people who enabled JS and makes the comments unusable with AMP. These are the exact problems I set out to solve!!! If you want these problems please use CComments. It does have AJAX support but it comes with all the drawbacks I mentioned as a result. 

Yeah. It’s 2020. You can either have plain text, AJAX submitted comment like FB or you can have real HTML comments in AMP pages. Take your pick. I find AMP to be far more useful in driving traffic than making comments submission take 0.6s instead of 0.7s. I’d be a bloody idiot if I screwed my site’s growth to save so little time that you literally blink and you miss it...

**Comment by nikosdion** [comment]
I'd also like to clarify that submission of content over AJAX is neither a new concept for our company, nor something we brushed off without a second thought. We've implemented that in Akeeba Ticket System since 2013. It's those six and a half years of real world implementation experience that made me decide against implementing it in Akeeba Engage. Even in ATS we implement AJAX posting only for BBcode for the reasons I explained (we already did our R&D).

I am not saying no because I didn't think about it and I got all pissy with two people asking for that feature. I am saying no because I understand the implementation details and how the conflict with the core values of Akeeba Engage (security, performance, ease of customisation).

I also do understand where you're coming from. If you have tons of slow plugins and modules loading on your site your page load times are probably in the high 3 seconds or even more. If that's the case, you have an implementation problem. Fix your site's implementation first. I know that this sounds dismissive, arrogant even, but the past 7 years we went from a cobbled together site I was hastily updating for the better part of 5 years to one that has been professionally implemented, with a _custom built template, without using a template framework_. Ditching the template framework shaved off more than 2s of page load time. Minimising the number of modules and plugins shaved off another 1s. Now the site renders pages in ~0.6s, going over 1s only when listing a bazillion of tickets. I think it's not arrogance sharing a potential solution.

Regarding my comment about CComments, I did not meant to sound snarky or dismissive about it. It is a great comments extension and I was using it in the past. It does support AJAX posting of replies but because of that it has the drawbacks I explained. It no longer fulfilled my use case, that's why I wrote Akeeba Engage.

And here's the beauty of this. **There is no universal use case. No software can cater for all possible use cases at the same time**. That's why Free and Open Source Software gives us the freedom of choice. If my software's priorities don't match your needs and goals don't use my software. No hard feelings; no offence taken. Maybe CComments or Komento would be better for your use case. Just, please, don't _you_ be dismissive about my software and assume that I'm an idiot who doesn't understand AJAX. More so when you're talking to the developer who was the first to ever use AJAX in a Joomla component back in 2006. That's back in Joomla 1.0, before jQuery, before universal XmlHttpRequest support in all browsers. I think I know a thing or two about it :)

**Comment by maxim-pishnyak** [comment]
No AJAX? Fine. Why Engage is really better then Kunena's Discussbot, may I ask you, @Nikosdion?

**Comment by maxim-pishnyak** [comment]
No AJAX? Fine. Why Engage is really better then Kunena's Discussbot, may I ask you, @Nikosdion?

**Comment by nikosdion** [comment]
I never claimed Akeeba Engage is better than anything else. I only said it's _different_. Please don't put words in my mouth.

Superficially, every comment solution for Joomla is about having comments on your site. However, each one tries to solve a _different problem_.

Kunena Discussbot makes the assumption that you want to discuss your articles in your already installed Kunena forum, using the familiar interface of Kunena.

Akeeba Engage makes the assumption that you want standalone, threaded comments with an emphasis on display performance, security, structured data (“microdata”) and AMP support.

The two solutions are like a butter knife and a stake knife. They are both great knives as long as you use them for their intended purpose. The butter knife is excellent at spreading butter. The steak knife is excellent at cutting cooked meat. Neither can efficiently debone a fish. Which knife is better? You tell me.
