### ISSUE TITLE
Add additional user for notification per article

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#287]
**Is your feature request related to a problem? Please describe.**
We have a closed website, only accessible to registered users. Also we have a small group of website editos. Sometimes those editors add content that is received from a community member and they want that user to be notified of comments from other users on 'their' artivle. Or there might be other situations you want to notify another user of comments to a specific article.

**Describe the solution you'd like**
It would be great to be able to add an extra CMS user (or email addsess)  to an article so notification of new replies will be send to that user / e-mail as well. Maybe using a tag or a custom field?

**Describe alternatives you've considered**
We could also change the author of the article to the user that need to be notified. But I am not sure if that is already possible now? The downside is this article will lose it's author ID when a user is removend from the system. 

**Why do you think this is relevant to people other than you**
Not sure...

**Comment by nikosdion** [comment]
The correct solution is to set up a user for the author. 

Having a feature where you put random email addresses to be notified is NOT a good idea. It creates the potential for abuse, it makes unsubscribing from emails very complicated, it makes the implementation of sending emails too complex and very finicky, etc.

As for this:

> The downside is this article will lose it's author ID when a user is removend from the system.

If you _delete_ users, you are using Joomla! wrong. Of course you will have problems by doing that. 

Use the Privacy component to create a Remove request. It does not delete the user; it pseudonymizes it. There is still a user with a fake email address, a username like "user1234", and a full name like "Deleted user 1234".

Even before the privacy component, that was the recommended course of action for users who have created something on the site: use a fake name, username, and email address, then turn off their Receive System Email. It's been the case since at least Joomla! 1.5, maybe 1.0 (I really can't remember what the user management looked 18 years ago).

**Comment by nikosdion** [comment]
BTW: "you are using Joomla wrong" is meant to be read like Apple's statement of "you are holding it wrong" for iPhone 4, i.e. yes, you are doing something which is possible, completely intuitive, but not at all how the system was designed to be used. Not that you'd know, because nobody bothered documenting this, and the intended design is counter-intuitive as heck.

**Comment by jjnxpct** [comment]
Hi Nicholas! Thanks for your reply. Of course you are right about deleting users. But I do think it might be confusing for managers to still see users in the user management that should not be there. So maybe it would be nice to be able to 'archive' users somehow. Anyway, this is off topic ;-) We will use the author field to add a registered as author to it so this user will receive the notifications. 

Still, maybe there are situation you want to notify multiple users (not random emails) about comments. For now, I think we are good.

**Comment by nikosdion** [comment]
Remember, these users do NOT retain the user name, email address, or username. I honestly believe that a user named "Deleted user 1234" with a username of "user1234" is pretty obviously a user entry removed upon request (exercising their rights under the GDPR). If your managers really cannot grasp that ridiculously easy concept I think you have a far more important problem in your hands…
