### ISSUE TITLE
Flag as spam does not notify comment manager

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#303]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Mark a comment as possible spam.

### Expected result

Managers receives a mail stating that a comment is a possible spam.

### Actual result

No mail is sent.

### Troubleshooting already performed

I thinks `sendEmailsAfterPostCreation` event is called, probably because `onComEngageCommentTableAfterCreate` is not properly fired up.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.4.1
* **PHP version**:  8.2.12 
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Arch
* **My device's Operating System version**: N.A.
* **Browser**: All
* **Browser version**: N.A.

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: MariaDb 10.11.4
* **Server type**: NginX
* **Server version**: 1.22.1
* **Hosting company / Local server**: Local Raspberry Pi 4
* **Server Operating System version**: Debian 12

### Additional comments
None

**Comment by nikosdion** [comment]
This feature was never meant to send an email since it is only exposed to comment managers. Remember, comment managers are those users who have the Edit State (`core.edit.state`) privilege. This is, indeed, a requirement for marking a comment as possible spam, definite spam, or ham (not-spam).

Therefore, you are talking about an action taken by a comment manager. It makes no sense notifying the same person and other comment managers for an administrative action taken by a comment manager. That's pointless noise.

Regarding your comments, kindly note that the method `sendEmailsAfterPostCreation`, if its name was not entirely evident, is also explicitly documented in its docblock as something which is only meant to be triggered for **NEW** comments, not comments which are edited, or whose state is changed:

```
	/**
	 * Automatically triggered right after Akeeba Engage saves a NEW comment record to its database table.
	 *
	 * @param   Event  $event  The event we are handling
	 *
	 * @return  void
	 * @since   1.0.0
	 */
```

Remember, that there are different mail templates to notify the author and the managers about the same _new_ comment being submitted, including one (`engage.spam`) which is sent to comment managers and only when a comment is _automatically_ detected to be spam. The fact that it's for new comments only is immediately evident by the wording of the email:

> A new comment was filed on “{CONTENT_TITLE}”. The comment is currently marked as spam.

Therefore, there is no bug here. This is how it was designed to work.
