### ISSUE TITLE
Engage and Google search Console error

### ISSUE THREAD

**Issue by Eddy-vh** [akeeba/engage#313]
### Discussed in https://github.com/akeeba/engage/discussions/312

<div type='discussions-op-text'>

<sup>Originally posted by **Eddy-vh** February 24, 2024</sup>
Hello.

Google Search Console shows me an error concerning comments. The "datePublished" field, which is required, is missing.
What can I do to correct this error?
![capture](https://github.com/akeeba/engage/assets/3940336/869f1694-fead-4627-818b-960963d47ec4)

Thank you very much for any information on this subject.

Have a nice week end.
Eddy</div>

**Comment by nikosdion** [comment]
Try the changes you see [here](https://github.com/akeeba/engage/commit/ef1a94633e5ede3be6b5a172e0ec3c47c5e3dc70), and remember to clear Joomla's cache. Then, try again. It should now be picking up the published date.

**Comment by Eddy-vh** [comment]
Hi Nicholas,

I've made the change in the Engage file, but more importantly in the override I'm using.
The code now seen by Google is what we expected but the error persists.
<img width="1818" alt="capture_2" src="https://github.com/akeeba/engage/assets/3940336/74ad3d2e-caa2-43f8-868e-8c36f637b81b">
Here's a relevant page if it helps.
https://www.breezingforms.eddy-vh.com/utilisation/breezingforms-validation-elements

Regards
Eddy

**Comment by nikosdion** [comment]
The problem is the location of the microdata, not its content. Please see [these changes](https://github.com/akeeba/engage/commit/bdc4dafcbc403f5e1e0641339502632e7d5680b5#diff-09be04b0439a827df55d95cb12b8448f244754cdf6ca13ff11658e3266f43a8e).

To understand what I am talking about compare the schema.org validation results [for your site](https://validator.schema.org/#url=https%3A%2F%2Fwww.breezingforms.eddy-vh.com%2Futilisation%2Fbreezingforms-validation-elements) which does not have these changes compared to [my site](https://validator.schema.org/#url=https%3A%2F%2Fwww.dionysopoulos.me%2Fmaking-a-portable-full-installation-of-ubuntu-on-a-usb-hdd.html%3Fhighlight%3DWyJ1YnVudHUiXQ%3D%3D) which now has the changes applied.

**Comment by Eddy-vh** [comment]
Hi Nicholas,

Google is in the process of validating the correction. Thank you for your quick response and the solution to this problem.

Eddy
👍

**Comment by nikosdion** [comment]
You're welcome, and thank you for the useful info which helped fixing this issue!
