### ISSUE TITLE
Global settings hidden...

### ISSUE THREAD

**Issue by jjnxpct** [akeeba/engage#316]
After installing the extension I first disabled the global 'show comment section' option so we can set this at the article category level. But in the global extension settings the options below this 'show' selector are hidden from the view. So when I wanted to change some options I thought they were not available globally. Because the did not show. So I started to set the,m on the category level, but I found it weird that there was a 'use global' value when I could not find them in the global setting ;-)

I do believe the setting in the 'hidden;' global values are active. So when you need to change a global value you need to enable the comments globally, change the setting, then turn them of globally again.

My suggestion would be not to hide those settings when ' show comment section' is set to 'hide' so those ption are still visible and van be changed.

**Comment by nikosdion** [comment]
Joomla! does not make this possible, unfortunately. The Show On feature only works based on options displayed _on the same form_, not an option set up in a _different component_.

If you have the kind of setup you have, you should not be relying on "Use Global" at all. Set all options at the category level.

**Comment by jjnxpct** [comment]
OK, thanks. 

But I am correct that the 'hidden' options that are set globally will work when the category option is set to 'use global'? So if we do want to use the global settings but not the 'show' option we still can use those settings globally? We just need to turn show on and off to set them?

When there are a lot of catergories I could imagine setting those option globally would be easier. 

But setting it at the category level is still a good sugestion. I just wanted to popint out it's a bit confusing to see options set to 'use global' while they don't show up in the global settings.

For me, I now how to find and set these options now, so I'm good to go ;-) Thanks.

**Comment by nikosdion** [comment]
> I am correct that the 'hidden' options that are set globally will work when the category option is set to 'use global'?

Yes.

>  So if we do want to use the global settings but not the 'show' option we still can use those settings globally?

You should _not_ select "Use global" in your use case.

> When there are a lot of catergories I could imagine setting those option globally would be easier.

Correct. It also means that in this particular use case you're using the product wrong. You should have the default, component-level (global) settings set to allow comments, then **disallow comments on the categories you do not want comments**.

The idea is that you should always set up your component-wide settings to what the majority of categories need, so that you have to override settings in the minority of categories.

>  I just wanted to popint out it's a bit confusing to see options set to 'use global' while they don't show up in the global settings.

I agree with you, but the problem is that options in Joomla! are rendered with an XML form. Since the form is static, you get "Use global" as an option even though it's not appropriate in context. The solution is either very complicated code or common sense. One of them is far more expensive than the other ;)
