### ISSUE TITLE
"Edit by" account is wrongly displayed

### ISSUE THREAD

**Issue by NicolasDerumigny** [akeeba/engage#322]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Edit a guest comment.

### Expected result

The "Edit by" info displays my pseudonym. 

### Actual result

The "Edit by" info displays the guest pseudonym.

### Troubleshooting already performed
In https://github.com/akeeba/engage/blob/2f41f60e260115c211dee5279e2f5fa6ec783997/component/frontend/tmpl/comments/default_list.php#L235 :

```diff
-                               <?= Text::sprintf('COM_ENGAGE_LBL_COMMENT_MODIFIED', Factory::getDate($comment->modified)->setTimezone($this->userTimezone)->format(Text::_('DATE_FORMAT_LC2'), true), $comment->name ?: UserFetcher::getUser($comment->modified_by)->name) ?>
+                               <?= Text::sprintf('COM_ENGAGE_LBL_COMMENT_MODIFIED', Factory::getDate($comment->modified)->setTimezone($this->userTimezone)->format(Text::_('DATE_FORMAT_LC2'), true), UserFetcher::getUser($comment->modified_by)->name?:$comment->user) ?>
```

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 5.1.2
* **PHP version**:  8.2.20
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Arch
* **My device's Operating System version**: N.A.
* **Browser**: All
* **Browser version**: N.A.

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: MariaDb 10.11.4
* **Server type**: NginX
* **Server version**: 1.22.1
* **Hosting company / Local server**: Local Raspberry Pi 4
* **Server Operating System version**: Debian 12

### Additional comments
None

**Comment by nikosdion** [comment]
Your “fix” introduces a privacy problem.

Someone submits a comment. A few minutes later they edit it. A year later, they create a user account with the same email address they used to submit the comment.

The way it is now: the original name used for the comment is printed out.

The way you changed it: the user account's name is printed out.

The latter will catch some people by surprise, as they may not realise their old comments submitted pseudonymously using just an email address will now be showing the name they put in their user account. This is also an issue with the created by name, which is why we have https://github.com/akeeba/engage/blob/bdc4dafcbc403f5e1e0641339502632e7d5680b5/component/frontend/tmpl/comments/default_list.php#L37-L40 using a logical OR instead of AND.
