### ISSUE TITLE
Add shortcode for display comments

### ISSUE THREAD

**Issue by kernusr** [akeeba/engage#36]
Please add the ability to embed comments with shortcode like {engage} for call comments from current article.

**Comment by nikosdion** [comment]
I suspect what you really want is to only allow comments on specific articles rather than all categories or all articles in a category. This is already possible.

You can install Akeeba Engage and set Comments Interface to No in the component options or the category. Then for each article you want to allow comments for set the Comments Interface option in the Comments tab to Yes.

There are many good reasons why I did not implement Akeeba Engage as a short code.

1. Shortcodes are processed by a common event handler and not just for articles. This means that suddenly you have comments in weird places like Custom modules or messages in third party components. These kinds of text do not have a Joomla `asset_id` and usually not an identifier at all which makes it impossible to keep comments for them (comments need to belong to _something_ and that something needs to have a unique identifier). This technical reason is the tombstone for that approach but I will also present all the other reasons why I chose not to go that route – I really did put _a lot_ of thought behind this deceptively simple component.

1. Why should we even ask people to remember to include an `{engage}` shortcode in their articles to enable comments? It's opaque (there is no interface you can click through, it's something you need to remember without any cue or clue when writing an article). It's error prone. You can easily mistype, misremember or misplace the shortcode. It's unnecessary. Joomla provides an event handler _specifically_ for the purpose of displaying content below each article when displayed in the full article view. In short, it's an inelegant solution which screams that the person implementing does not understand anything about Joomla or usability.

1. What happens if you turn off the Engage content plugin? With shortcodes you end up with an unparsed shortcode in your content that sticks out like a shore thumb and makes your site look unprofessional and abandoned. With the current implementation the comments simply disappear from view – as they should. Unlike most developers I do not suffer from the illusion that users will want to keep my software on their sites forever. Especially sites which have a lifespan of a decade or more.

1. Using a shortcode essentially puts the comments interface in random places in your article. This doesn't make sense from a UI or UX perspective. Having the comments in the middle of an article is horrid. Sure, you could use the shortcode as a "switch" to render comments at the end of the article. However, this runs head first into the two previous problems making both a usability and a technical implementation nightmare. Why not have a toggle switch in the article options? So of course a toggle switch in the articles options, under the aptly named Comments tab, is what I implemented.

1. What happens if you put two, three, fifty shorcodes in the same article? Do we use them as a toggle and replace them with an empty string, essentially creating blank paragraphs in your content? Do we render the comments interface in the first encounter? The last encounter? One of the middle encounters? It's an undefined problem which is guaranteed to dissatisfy most people since all mutually exclusive solutions are equally valid and invalid. Eventually you need to add an option in the article to choose which shortcode will render the interface... wait! We just came back to adding options to the article. Doh.

1. Assuming there's a magic solution to all of the previous problems (there isn't; this is just for the sake of argument) what happens if you are trying to display multiple comment interfaces on the same page? This is confusing for the user and extremely complicated to implement. Each comment interface would need to have its own identifier and the JS would need to be able to deal with that. This is a minefield for bugs.

1. How can you make sure you do not show comments in a blog listing, a newsletter (think AcyMailing), a print preview etc? The answer is you can't, because shortcodes are processed in all these contexts! The solution is to use the event handler explicitly used when displaying an article – that is how we are currently implementing it.

Shortcodes are a really uncivilised way of implementing any feature which adds an additional interface to a full article display, be it comments or anything else. My job as a developer is to make use of the correct event handlers in Joomla to give you a seamless experience which doesn't make you think and doesn't cause undefined problems with a multitude of mutually exclusive solutions to spring up.
