### ISSUE TITLE
Comments not using Timezone for Date/Time

### ISSUE THREAD

**Issue by NetDirection** [akeeba/engage#58]
### Steps to reproduce the issue

Write a comment.  View it

### Expected result

Comments should show date with regard to timezone

### Actual result

Comments are saved and displayed with GMT instead

### Troubleshooting already performed

I found a fix by inserting into:
/public_html/components/com_engage/ViewTemplates/Comments/default_list.php 
(after line 61:- $commentDate   = new Date($comment->created_on);)

$commentDate->setTimezone(new DateTimeZone(JFactory::getUser()->getParam('timezone', JFactory::getConfig()->get('offset'))));

This applies the user's timezone to the date and falls back to the default Joomla one if not set.

It leaves the date in the database as GMT

### System information
* **Joomla! version**: 3.9
* **PHP version**: 7.2
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Linux
* **My device's Operating System version**: Ubuntu 18.04
* **Browser**: Firefox
* **Browser version**: 6.6.6

### Additional comments

Note - I've posted a fix.  Feel free to apply it to the main program. :)

**Comment by nikosdion** [comment]
Thanks for the heads up!

Your solution is mostly correct but I chose to follow a slightly different approach. Instead of going through Joomla's Registry objects twice for every comment I am caching this information on View creation. This saves a few milliseconds for every page load that has comments :) I am also fixing the AMP view which you are not using but is similarly affected.

**Comment by NetDirection** [comment]
Thanks :)
