### ISSUE TITLE
Engage: Reply to Comment

### ISSUE THREAD

**Issue by trlbldr1** [akeeba/engage#61]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Attempted to Reply to a published comment on my blog (https://www.pathkeeper.net/by-the-way/for-cause.html#akengageCommentForm)

### Expected result

My reply would be accepted and published.

### Actual result

Received this system response: The application has stopped responding

### Troubleshooting already performed

Checked Engage configuration against documentation; no problems there.

#### Mandatory information

* **Joomla! version**: 3.9.23
* **PHP version**: 7.4.13
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **My device's Operating System**: Windows 7
* **Browser**: Firefox
* **Browser version**: 84.0.2

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by nikosdion** [comment]
Do note that your **browser** pooping its pants and closing IS NOT an issue in Akeeba Engage, Joomla or your web server. It's something to do with your browser, your Operating System and the software running **ON YOUR COMPUTER**.

Your real problem is that you are using an antiquated operating system from 12 years ago which Microsoft officially announced End of Life over a year ago, in 2019.
