### ISSUE TITLE
The link in the PHP version notification leads to 404

### ISSUE THREAD

**Issue by Kostelano** [akeeba/engage#72]
The link in the PHP version notification leads to 404.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/107153525-b34a9900-6976-11eb-8148-084c14e95185.png)

In addition, it may make sense to "drive" all notifications about the PHP version into language constants for translation.

Of course, the essence of the notification is clear and so. There are also all kinds of translators. But if there are localizations of the extension, then it makes sense to translate everything and not leave the part in English.

**Comment by nikosdion** [comment]
There's a missing `i` in the URL. I added a redirection on our site to fix that. Moreover I fixed that in the common message templates used in all of our software.

The messages about PHP versions, the error handler page, the incompatible PHP error page and the missing FOF framework error page are stored in a central, private repository and copied over to all of our software. The file with the PHP version warnings is used in 12 Joomla extensions, Kickstart and two WordPress plugins.

Herein lies the problem with translations.

First, it's not a given that these message files will appear in Joomla or even a specific Joomla version. Therefore they'd need to do some complicated shit to figure out which translation method applies (even under Joomla you can have two different methods depending on the version).

Second, it's not a given that a translation message will exist at all. For example, the unhandled PHP exception error page may display in such a context.

Third, it's not a given that the language files will have loaded. The unhandled PHP exception may and the unsupported PHP version page will display before Joomla loads the extension language files.

Fourth and most important: I need to be in complete control of the **EXACT PHRASING** of the message. People get extremely offended extremely easily. I've had people telling me to go fuck myself for being a useless developer and a PHP corporate shill (never mind PHP is FOSS and there's no corporation behind it, we're talking about fucking morons here) just because my software told them to upgrade their PHP version that was 3 years out of date because it has known security vulnerabilities. The reason for the outpour of abuse was that I hadn't yet added the link to the official PHP page and hadn't added the part of the message that reads "even if your host or your Linux distribution claim otherwise. The PHP language developers themselves have said time over time that not all security vulnerabilities fixes can be backported to End-of-Life versions of PHP since they may require architectural changes in PHP itself." Seriously.

On the same note, I have had problems with translators before misreading the message and translating it to mean the exact opposite of what I wrote. For example, telling people to keep using their outdated version and NOT use a new version. In other cases I had people send me streams of abuse because they didn't like the translated term or found a minor typo, none of which is under my control (and I had been making it explicitly clear that translations ARE NOT handled by our company, they are volunteer efforts).

To sum it up, the reason these message are untranslated is that there is a very vocal minority of totally batshit people. I'd rather be in absolute control of the messaging that matters and rub it to the face of the morons who try to tell me I meant something different than what I wrote. Sorry. I have to do what I have to do.

**Comment by Kostelano** [comment]
An exhaustive answer, thanks :)
