### ISSUE TITLE
Class 'FOF30\Date\Date' not found

### ISSUE THREAD

**Issue by sjys** [akeeba/engage#75]
After I upgraded to v2.0.0 I get "Class 'FOF30\Date\Date' not found" fatal error.

### Steps to reproduce the issue

When I publish a comment and go to the page to visit the comment on the page I see the "Class 'FOF30\Date\Date' not found" error.

### Expected result

The comments should be displayed

### Actual result

I get the "Class 'FOF30\Date\Date' not found" fatal error.

#### Mandatory information

* **Joomla! version**: 3.9.25
* **PHP version**: 7.4.16
* **Am I using HTTPS**: Yes
* **Server Operating System**:  Linux

**Comment by nikosdion** [comment]
This is a Joomla bug, yes. One that has existed since 2007 and I've been reporting since 2014. Joomla sometimes does not copy all files and folders when installing an update.

Download the update ZIP file and install it twice in a row (using Extensions, Install, Upload & Install), _without_ uninstalling Akeeba Engage before or in between. This will copy all the correct files.

If you had done any template overrides you will need to update them.

**Comment by sjys** [comment]
I did it but I get this warning 
"
You have a newer version of FOF installed. If you want to downgrade please uninstall FOF and install the older version.
Extension Update: Custom install routine failure.

You already have a newer version of Akeeba Frontend Framework installed. If you want to downgrade please uninstall Akeeba Frontend Framework and install the older version.

If you see this message during the installation or update of an Akeeba extension please ignore it and the immediately following “Files Install: Custom install routine failure” message. They are expected but Joomla! won't allow us to prevent them from showing up.
"

I think it's because of the new version of the FOF file which recently has been updated.

**Comment by nikosdion** [comment]
As noted:
> If you see this message during the installation or update of an Akeeba extension please ignore it and the immediately following “Files Install: Custom install routine failure” message. They are expected but Joomla! won't allow us to prevent them from showing up.

**Comment by sjys** [comment]
Yes but my issue not resolved, I still get the fatal error.

**Comment by nikosdion** [comment]
Have you made any template overrides?

**Comment by sjys** [comment]
No, just some string overrides.

**Comment by nikosdion** [comment]
There are no references to FOF30 (FOF 3.x) in Akeeba Engage 2. Therefore your issue happens because a. the update was not installed properly or b. you have template overrides.

Installing the extension **twice in a row** typically resolves the first problem. If it didn't delete the following folders and the install the Engage 2.0.0 package again:
* administrator/components/com_engage
* components/com_engage
* plugins/actionlog/engage
* plugins/content/engage
* plugins/datacompliance/engage
* plugins/engage
* plugins/privacy/engage
* plugins/system/engage
* plugins/user/engage

As for the second problem you say that you have no template overrides. If my suggestion doesn't work then you definitely have made template overrides.

**Comment by sjys** [comment]
Yes, you're right, my template already has a template overrides. I just change FOF30 to FOF40 and it works.
Thanks.

**Comment by nikosdion** [comment]
You're welcome!
