### ISSUE TITLE
Issues in selction box notify author and user in articles and categories

### ISSUE THREAD

**Issue by NetSecond** [akeeba/engage#83]
Hi,

after fresh installation of version 2.0.1, there are 2 issues (configure articles comments & configure categories comments):

![engage_problem_2](https://user-images.githubusercontent.com/26506313/118402809-da96bd80-b66b-11eb-9785-7ff432f14966.jpg)

If i check it at the global comments options, I see the correkt "yes/no" buttons but in articles and categories I see this mysterious drop down boxes with only one option "1 Ja" (see picture).

The german text comes from the german joomla language, the engage is original in english.
I have a translated german version but there are the same issues, but then in german.

I checked the parts in database and files (differences between global, articles and categories, but found nothing what is different.
Why i get in global config the both buttons and in articles and categories this dropboxes at inform author and user ??

**Comment by nikosdion** [comment]
I have no idea what is that. Here is how it actually looks:
![Screenshot 2021-05-17 at 10 00 20 AM](https://user-images.githubusercontent.com/256041/118445111-b3d19900-b6f6-11eb-93fb-eef94e41efaa.png)

And here is the very standard code which renders it like that: https://github.com/akeeba/engage/blob/5a8f916164f5c80a73b5f2f37967152e5bf16b2b/plugins/content/engage/forms/engage.xml#L92-L118

You say that it happens on a clean installation. I installed a new Joomla 3.9.26 site and Akeeba Engage 2.0.1. I can't reproduce this. I can also see why it cannot be reproduced. It would require the "fancyradio" field type to be undefined. This is defined in the component's administrator area which simply includes the common code from FOF.

The only thing I can possibly think of is that FOF is not actually fully updated on your site because of a Joomla extensions installer bug that has existed since 2007 and Joomla 1.5.5 (I wish I was joking...). Delete the libraries/fof40 folder (AND ONLY THAT FOLDER!) from your site. Download the latest version of FOF from https://www.akeeba.com/download.html. Extract the ZIP file. Rename the extracted folder fof to fof40. Copy that folder inside your site's libraries folder so now you have again a libraries/fof40 folder.

**Comment by NetSecond** [comment]
In global configuration everything is perfect:

![notifyglobal](https://user-images.githubusercontent.com/26506313/118492703-90bbdf00-b720-11eb-8dc4-f231d0522556.jpg)
(language does´t matter, in english is the same)

So I don´t understand, why it is not in "articles" and "categories":
![notifyarticle](https://user-images.githubusercontent.com/26506313/118492994-edb79500-b720-11eb-9ee6-a8a8bae1f52a.jpg)

But I will check everything again und look for the FOF thing ....
Thanks and regards
NetSecond

**Comment by nikosdion** [comment]
It's a different form file and field for global configuration and categories/articles. The former is in the component, the latter is in the content - Akeeba engage plugin. That's why I linked to the relevant file.

Have you tried the double installation I proposed?

**Comment by NetSecond** [comment]
I checked everything again and there were the new 4.0.6 fof40 files already installed.
But I deleted the fof40 folder and uploaded the files from your link, no change.

I forgot to say, that I have installed akeeba backup before, that was the only package and that was maybe the reason for the warning after installation.

Ok, I don´t find the reason for this, I checked forms, database and so on.
In reason, that I can live with that (both is in DB on 1 / activated as I need), I will  let it as it is.

Thanks for your time and when I know, that it works on a completely fresh installation, than I can fix it, when I have time to reinstall my productive website.

Regards
NetSecond

**Comment by nikosdion** [comment]
OK, this is officially too weird. Can you please check the file `plugins/content/engage/forms/engage.xml` and tell me what the lines 92 to 118 read?

Also, which is the exact version of Joomla and PHP you are using? I have tested this feature with Joomla! 3.9.24, 3.9.25 and 3.9.26 and PHP versions 7.2, 7.4 and 8.0. Since this field relies on a core Joomla layout I am wondering if an older version of Joomla or PHP may be doing something wonky.

Finally, can you please check with a different browser? If you're on Windows please use [Iron, Portable Edition](https://portableapps.com/apps/internet/iron_portable). This is a self-contained Chromium-based browser which ships without any extensions. I am wondering if an extension picks up the field Joomla's trying to render and somehow messes it up. Unlikely, but given the number of unlikely and borderline impossible problems I've seen the last 15 years I'd like to have that base covered as well.

**Comment by NetSecond** [comment]
<field
                    name="comments_notify_author"
                    type="fancyradio"
                    label="PLG_CONTENT_ENGAGE_COMMENTS_NOTIFY_AUTHOR_LABEL"
                    description="PLG_CONTENT_ENGAGE_COMMENTS_NOTIFY_AUTHOR_DESC"
                    class="btn-group btn-group-yesno"
                    useglobal="true"
                    default=""
                    showon="comments_enabled!:0"
            >
                <option value="1">JYES</option>
                <option value="0">JNO</option>
            </field>

            <field
                    name="comments_notify_users"
                    type="fancyradio"
                    label="PLG_CONTENT_ENGAGE_COMMENTS_NOTIFY_USERS_LABEL"
                    description="PLG_CONTENT_ENGAGE_COMMENTS_NOTIFY_USERS_DESC"
                    class="btn-group btn-group-yesno"
                    useglobal="true"
                    default=""
                    showon="comments_enabled!:0"
            >
                <option value="1">JYES</option>
                <option value="0">JNO</option>
            </field>

**Comment by NetSecond** [comment]
Joomla! 3.9.26 Stable [ Amani ] 13-April-2021 15:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
or
Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT

PHP 8.0.3 (tested also with PHP 7.4.16 / doesn´t matter / same problems)
Database 5.5.5-10.3.24-MariaDB-log-cll-lve

Tested in MS Edge (Chromium Version)

In Firefox, there are only empty fields.

In Opera same problem as in Edge, 2 DropDown fields with "1 / Ja".

In Iron Portable, same problems like Edge and Opera.

**Comment by nikosdion** [comment]
There was indeed a problem. I couldn't reproduce it because I had my other software installed which already loaded the custom form field that rendered the multiple choice field.

I will be making a new release next week with this change included.

**Comment by NetSecond** [comment]
Thank you very much and also for your great work on Engage.
