### ISSUE TITLE
Engage and Yootheme Pro [OTHER]

### ISSUE THREAD

**Issue by jrlyon** [akeeba/engage#89]
Hi,

I am trying to use Akeeba Engage on our site.

Site is built with Yootheme Pro latest version.

I have followed installation instructions. All plugins have been activated.

In a Blog Category (News) , I am not able to activate comments for all articles showing up in this particular category.

Actually nothing concerning Akeeba Engage is showing at bottom of each article.

What am I doing wrong ???

Thank you for help.

Rgds from France

Jean

**Comment by nikosdion** [comment]
The Content – Akeeba Engage plugin responds to Joomla's onContentAfterDisplay event. When you are displaying a single article it will returns all comments and the new comment / reply interface. When you are displaying a content category or featured articles it will only return a summary (e.g. "1 thought on Your Article Name Here" if there's one comment).

Whether this additional text is rendered on the page you see is up to the template. Joomla's default templates and the templates I build for my own sites do that. Third party templates should do that if they want to call themselves fully Joomla compatible. If you're not sure if this is the case or if there is a template option which may be affecting whether the content from that event is displayed you need to ask your template provider.

I have seen a lot of problems with third party templates not supporting Joomla features, like this one, which have existed for nearly a decade. I have stopped using ready made templates since around 2013. I'd much rather build my own template. It's not that hard and I know that it works because I start with a solid base, either Joomla's built-in templates or one from a trusted developer who follows Joomla's standards.

**Comment by jrlyon** [comment]
Thank you, I understand the problem.
Case closed.
Best from France
Jean

**Comment by nsheehan** [comment]
For future reference.... Done easily in YTP however not obvious.
https://yootheme.com/support/question/137639

**Comment by nikosdion** [comment]
@nsheehan Thank you for the heads up! This is a really non-obvious option 😯 I think I will have to add a note in our documentation somewhere.

**Comment by nikosdion** [comment]
The documentation [is now updated](https://github.com/akeeba/engage/wiki/Main-Concepts#how-comments-are-rendered).
