### ISSUE TITLE
Move published/unpublished state for new comments into ACL

### ISSUE THREAD

**Issue by Giuse69** [akeeba/engage#90]
First of all thanks for this components.
I am asking here to move the option to set new comments as published/ unpublished into ACL. In this way we can decide for example that guest comments must be moderated while comments from registered users can be immediately published.
Thanks for your attention

Giuse

**Comment by nikosdion** [comment]
First of all, no, that is not how Joomla ACLs work at all. ACLs control the actions a user can take. Submitting a comment **is** an action, controlled by the Create privilege. Whether that comment will be published, an email will be sent etc are **NOT** user actions and they shouldn't be controlled by ACLs. But that's not even the point.

If you are worried about spam you can use Akismet and/or a CAPTCHA. You can also require user registration to post comments, probably using something like Akeeba SocialLogin to make the signup and sign-in experience easier. If you think this won't work and you'll need to review comments then you really don't want me to implement a feature which bypasses your global, category or article level choice of requiring comment moderation before comments are published.

**Comment by Giuse69** [comment]
Ok for the ACLs, it's not a user action control, even if in a stretched sense it might be giving the user the grant to publish a comment or to submit a comment :).
Anyway since you have an option to set moderation ora not, in my opinion that might be extended to a 3 value option: publish for all, publish for registered, publish for none. Spam protection is different aspect than moderation, for me it can make sense to setup publish option differently for guests. It was just a feature request.
Best regards

**Comment by nikosdion** [comment]
I will need you to tell me your use case before I agree to implement such a feature.

The reason sounds totally non-obvious to you as demonstrated by your proposed implementation which is just plain wrong. Remember that this is mass distributed software which needs to simultaneously satisfy the needs of all of its users, not throw 99.999% of its users under the bus to satisfy the needs of a small handful. So please do let me explain what goes through my mind when I read your feature request.

Right now the comment publishing choice is binary: publish for all or publish for none (unless you can already publish comments in which case it would be dumb to not publish the comment you'd be publishing yourself). If we add a "publish for some" option the question becomes "publish FOR WHOM?".

In your very narrow use case it's "publish for Registered". However, someone else comes and says they don't want every registered user to publish comments. They want to sell that privilege so it should only be specific user groups. If you really think about it, it has to be changed from a binary switch to a multiple user group selection field. But this causes the problem that existing installations can't be upgraded since these settings are stored inside a JSON field in the `#__extensions`, `#__categories` and `#__articles` tables. We'd have to go through each and every record, parse the JSON, see if these options are set etc. This would make the upgrade fail.

This leaves us with a bad UI choice. When you select the option to auto-publish comments we need to add another option called “Publish for these groups”. The problem now becomes what is the default value for that. The default value is hard-coded in the XML file but I can't know in advance all the user group IDs you use on your site. I have to either go out on a limb and put the default Joomla user groups OR I have to add an option "– No preference –" which selects no user group and actually means “publish for all user groups” and use _that_ as the default.

This creates a UX and a maintenance issue. It is doable, but problematic. Before agreeing to something which will bring problems I need to know what exactly is your use case. If there's really no other way to do it I can consider this feature. If there is _any_ other way to achieve something similar I'd rather not introduce a feature that's confusing to the users and will cause me headaches in the implementation.

**Comment by nikosdion** [comment]
I am closing this issue, like the other two issues filed by this person, since he couldn't be bothered to offer a use case.

A feature request without a use case is a feature request automatically rejected. I have already explained that.
