### ISSUE TITLE
Feature: voting/like

### ISSUE THREAD

**Issue by Giuse69** [akeeba/engage#91]
Hi, can it be added as a future feature the possibility to vote/like and downvote/dislike comments?
It adds users involvements in commenting.
Thanks

Giuse

**Comment by nikosdion** [comment]
There are two ways to implement this, both with a lot of problems.

One way is to have Akeeba Engage work more like Stack Overflow. That is, order comments based on their “likes” and “dislikes”. However, this is a very different product to article comments. I'll say upfront that this ain't gonna happen.

The other way is to let people vote a thumbs up or thumbs down and show the tally with each comment. This sounds like a simple feature: two database fields, two buttons, one label. What could possibly go wrong?

Here's the thing. I am a senior developer and I can foresee everything that will go wrong and make Engage unmaintainable in this case.

Who can vote? Do you limit this by user groups? People who have commented on the article? In the latter case, what about people who commented with a guest account? Do you ask them to provide an email address to vote, which adds friction and CAN be abused? 

Then there's the obvious question of how do I prevent a flood of votes. We'd have to only allow each person to vote once. If we implement this client-side (with cookies) there are two ways to circumvent this. One, by using multiple browsers and devices. Two, by automating a browser to clear the cookies between votes. This means that votes need to be tracked by user ID and IP address. So instead of having two fields for upvotes and downvotes in each comment we now need an entire table with the details of each vote. This means that displaying comments requires doing a join query into a group by query which is O(N^2 * M^2) complex, i.e. the more votes and more comments you have the more disproportionately slower it becomes. This would make the comment system useless for more than a few hundred comments across all articles with up to a dozen or so votes each. Fixing that would require having BOTH the fields in the comments table AND the table of votes which now makes maintenance of the code a pain in the arse.

It keeps on getting complicated with guest comments and guest voting. How do you ensure that a guest commenter doesn't vote on their comment? There is no reliable way to do that — that's why commercial comment systems like Disqus and Facebook comments require you to be logged in to file a comment. Therefore implementing voting would mean that we'd need to remove guest comments. However, this is not feasible without removing the Create privilege from all ACL controls. But doing that also means that any and all logged in users can file a comment which further limits Akeeba Engage, removing an existing feature. The only way around that is to disable voting on guest comments which makes voting useless in your use case to begin with.

So, yeah, it does sound like a simple feature but the reality is that it's not. It works with Disqus, Facebook comments etc because they make the ASSUMPTION that all users logged into their platform can submit comments and like/dislike comments. However, the starting position of Akeeba Engage is that we offer you MORE flexibility that these third party platforms. Therefore this feature is a hard nope.

In the end of the day, if you want something that works like Disqus then there's, um, Disqus itself and the Joomla plugins to integrate it in your comments. If, instead, you want more flexibility about who can comment on what and keep your comments in your database then you use Akeeba Engage, without some features which require limiting this flexibility. My job here is to have a specific set of goals set for Akeeba Engage and the experience to know when to say no to features which would conflict with that. So here I am telling you no and WHY I am telling you no.

**Comment by Giuse69** [comment]
I was just thinking of the simplest feature of letting users hit like/dislike inline icons with prevention of multiple votes by checking cookies or IP,  without worrying of fake votes (it's not an official polling components, it's just for social involvement) or limitation by user groups or by being a commenter of the same article, a very open approach. Anyway you are the developer so you decide :)

**Comment by nikosdion** [comment]
As I said in your other feature request, this is mass distributed software. I can't publish a half-arsed feature which will cause problems to the majority of the users of the software.

It looks like you don't have a compelling use case for this feature, just a nebulous idea that this might somehow engage commenters in a non-specific manner. The most concrete idea you have about that is that only people who've commented on the same article should be allowed to vote. This brings his back to how do we determine that which, as I explained, is impractical if you have guest comments. That is to say, the most concrete aspect of your feature request requires removing the ability of guest comments which is a critical feature for the majority of the people using this software.

As a result I am closing this as something I won't be implementing. Sorry.

**Comment by Giuse69** [comment]
Actually I wrote the opposite, that we can avoid verifying whether voters are also commenters of the same article or not to keep it really simple. Like/dislike is a very widespread feature in all socials and many comment systems, so saying that I don't have a use case sounds strange to me. But anyway you are the programmer so I give up, it was a suggestion for enriching the component.

**Comment by nikosdion** [comment]
Please show me a comment system which allows everyone and their dog to freely vote on a comment **without** previously logging in and/or allows logged in users to vote more than once this side of 2010. You won't find any.

Now start thinking about WHY this is the case. You don't have to be a developer, just have basic reasoning skills.

In case you still don't get it. If you allow arbitrary, uncontrolled voting you are turning your comments section into a cesspit and committing server suicide. Person A has an axe to grind with person B. When person B comments, person A goes to the public comments section and sees the URL to downvote this comment. He then runs a simple loop to access that URL repeatedly and mercilessly. Even worse, he does that for all downvoting URLs of all comments of person B. Your server is now under immense load, pretty much a Denial of Service attack. If your server survives then person B sees that his comments have hundreds of thousands of downvotes, several orders of magnitude more than the up/downvotes of other comments. So of course he will say that your site is a piece of shit and 9 to our 10 commenters will agree. Congratulations, you just killed your "community" by allowing a toxic feature to run unchecked.

This should come as no surprise. This has happened between 15 and 20 years ago, in the primal forms of forums and social media. This is why all social media and comment systems which have a voting or reaction feature only allow that to signed in users.

So, as I said, the only RESPONSIBLE and MEANINGFUL way to implement this feature is removing the ability to post comments as a Guest user. However, in the context of what this here software does and what people are using it for, this would be detrimental.

At the same time you have offered zero compelling arguments for implementing this feature beyond the nebulous "other comment systems are doing it" (most comment systems for Joomla and WordPress don't and those who do require user registration for the painfully obvious and extremely important reasons you choose to gloss over) and "community" (with no supporting evidence).

So, no, I am not taking an arbitrary decision because I am the developer. I am taking a well documented decision because I don't implement bullshit features in a half-assed manner in my software for no reason — even more so when I can see well in advance that they would create a hell of a lot of problems rather than solve anything.

In the end of the day there's Disqus, there's Facebook comments and there are free of charge plugins to integrate them with Joomla.
