### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by jrlyon** [akeeba/engage#93]
Hi,
I think I have figure out the basics on how Engage works and it works well. Thank you !
But if no comments, first time comments appear as per attached screen shot Engage-1 with no title.
If one comment everything is back as expected as oper screen shot Engage-2.
Any idea why ?
Thank you for help
![Engage-1](https://user-images.githubusercontent.com/1286006/122666596-8d4bc580-d1ae-11eb-9afa-472b94fdd5fa.jpg)
![Engage-2](https://user-images.githubusercontent.com/1286006/122666598-90df4c80-d1ae-11eb-8c11-7e5aff74f04e.jpg)

Regards from France
Jean

**Comment by nikosdion** [comment]
I cannot reproduce this. I've tried this on my blog site, two different local development sites and a new Joomla installation. **HOWEVER** I can only try with the English and Greek language I have written and tested myself. 

It looks like the French language, which is a third party contribution, has a bug in the language string for the COM_ENGAGE_COMMENTS_ARTICLE_HEADER_N_COMMENTS_0 key in the `en-GB.plg_content_engage.ini` file. The current translation string reads `"Aucune opinion sur \"%2$\"."` instead of `"Aucune opinion sur \"%2$s\"."` Note the missing `s`? This is the problem.

I will fix it in the next release, but I don't know when that will be. You can make a language string override in the meantime.

**Comment by jrlyon** [comment]
Thank you for your very precise answer. 
I will fix it for the time being as instructed. 
Thank you
Regards from France

Envoyé de mon iPad. Jean 👍

**Comment by jrlyon** [comment]
I used the Joomla « language override » function to correct mistake and it works a charm…
Thank you,
Have a nice day !
Jean

**Comment by nikosdion** [comment]
You're welcome!
