### ISSUE TITLE
Latest Comments

### ISSUE THREAD

**Issue by jrlyon** [akeeba/engage#94]
All my request is in the title.
Does a "Latest comments" module exist ?
If Yes: where can I find it ?
If no: do you intend to create one in the future.
With this new module fully functionnal, I am ready to pay a subscription fee on a reasonable level...
Thank you and have a good day.
Jean

**Comment by nikosdion** [comment]
There is no such module yet. I'll make one but I can't give you a timeline just yet.

**Comment by jrlyon** [comment]
OK, I will wait ! but keep us posted...
Thank you
Jean

**Comment by nikosdion** [comment]
Let me give you an update. Joomla announced yesterday that Joomla 4 will be released August 17th. Right now it's all hands on deck to finalise various details so all of our software is fully ready for the stable Joomla 4 release and we have instructions for people upgrading from Joomla 3. This pushes all new feature implementations back.

The second point to note is that this MAY affect how this feature will be implemented.

First, we are going to rewrite this extension using core Joomla 4 MVC and Bootstrap 5 styling (for the backend; the frontend has its own CSS anyway) instead of our FOF and FEF frameworks. When this change is complete we will have two versions of Akeeba Engage. Version 2 will keep on running on Joomla 3 and will be receive limited support running on Joomla 3.10 until August 17th, 2023. Version 3 will only run on Joomla 4 and will be the main supported version. All new features will be implemented in version 3; version 2 will be frozen in time and only serve as a “stepping stone” of sorts, to allow people to upgrade from Joomla 3 to 4.

It is unlikely that we will implement this feature in version 2. Doing so would require us to do the same work twice. It will be implemented in version 3, i.e. after rewriting this extension for Joomla 4.
